### ISSUE TITLE
مرحبا أخ أحمد

### ISSUE THREAD

**Issue by s3bq8** [Ahmad-Faqehi/Twitter_Hashtag#1]
مشكور على السكربت الرائع ولكن لا توجد قاعدة بيانات

**Comment by Ahmad-Faqehi** [comment]
اهلاً أخوي. تفضل ملف قاعدة البيانات
https://github.com/Ahmad-Faqehi/Twitter_Hashtag/blob/master/hashtags.sql

**Comment by s3bq8** [comment]
مشكور
